name: Check

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install deps
      run: npm ci
    - name: Build
      run: npm run build
    - name: Unit test
      run: npm run test
