name: CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Install deps
      run: npm ci
    - name: Build
      run: npm run build
    - name: Unit test
      run: npm run test
